### PR TITLE
German translation / fix for image page redirection / remove unnecessary ISO_CODE constant

### PR DESCRIPTION
**Pull request by acrylian**

### CODE REVIEW

**Comment by acrylian** [comment]
Sorry, wanted actually to open a 2nd pull request for the image page fix but clicked to fast ;) Edit: Well, seems they are always collected in this one no matter. Anways :)

**Comment by bic-ed** [comment]
Hi, thanks for the translation and for the fix too. I was planning to work on image redirect to add the redirect code, that I forgotten, but also because it was working flawlessly on my local environment but not at all on my live server.

PS
I've also added the self-hosting fonts, I'll try to commit the changes this morning, before leaving for holidays, and perhaps make a new release already.

**Comment by acrylian** [comment]
Perhaps you might want to switch this popup opening to the the filename if possible as it makes nicer shareable single image links if the image page itself does not exist.

**Comment by bic-ed** [comment]
Anyway the redirect is still not working on my live server, but I really have to go now. Happy summer again!

**Comment by bic-ed** [comment]
Actually the redirect is working now. It was Multiverse not working anymore, because on live server I was running a not updated version of Zenphoto, and now I know that `printLangAttribute()` function was introduced in zp 1.5.7 :-)

My site is updated now and everything works fine, included the image.php redirect!

**Comment by acrylian** [comment]
All right, great ;-)

**Comment by bic-ed** [comment]
> Perhaps you might want to switch this popup opening to the the filename if possible as it makes nicer shareable single image links if the image page itself does not exist.

Not sure if I'm understanding what you mean here. Links to images are actually already in the canonical Zenphoto form, i.e. `/album-folder/image-filename.ext`. Title is only used internally to redirect from `image.php` to `album.php`. My only concern is about the possibility to have two images with the same title in the same album.

**Comment by acrylian** [comment]
Yes, exactly. Also if you have a title with special chars or a non European language it may also cause trouble depending on the server/browser whatever. Internally always the name – in this case filename and albumname naturally since you can have same named images in different albums – is the unique identifier of an image for that reason. If you must you can also use the ID.

**Comment by acrylian** [comment]
Also I noticed that the popup does not add the title so you have basically two urls for the image popup which is rather bad for SEO if you don't use the image php page. This is for example linked on many occasions like RSS, sitemap. I would generally recommend to provide one as a kind of fallback even if it may be more basic.

**Comment by bic-ed** [comment]
Hi, sorry for answering so late, it's non easy to follow this on holidays. I understand the SEO issue, on the other hand two pages with different title but same content are very bad too, am I wrong? Anyway, I'm afraid we should reprise this conversation later, after holidays.

**Comment by acrylian** [comment]
> I understand the SEO issue, on the other hand two pages with different title but same content are very bad too, am I wrong?

No problem. Yes,indeed  same content on two pages/URL is bad as well. I am not sure if the popup really counts as a "page" though as it is just opening an image via JS from the album page and is HTML and structure is different. If the image page lists for example tags and other additional stuff it might not be "the same".

Anyway, not a pressing need and has time until after your holidays.

**Pull request merged**
