### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by fretzl**
Btw, I think "pupup" should be "popup"

### CODE REVIEW

**Comment by bic-ed** [comment]
Hi Fred, you are right, thanks!
I'll change it right now, but then you and Malte will have to re-update the translations? Or may be I can do it myself by just removing the fuzzy state that will appear after the typo fix?

How come I see all of those old commits in this pull request?

**Comment by bic-ed** [comment]
Well, I'm merging this and then update it after the typo fix. Thank you very much!

**Comment by fretzl** [comment]
> How come I see all of those old commits in this pull request?
I was asking myself that too. I'm really no good at GitHub ;-)

**Comment by bic-ed** [comment]
I managed to update the fuzzy state after fixing the typos, so you don't need to update the translation again. ;-)

**Comment by fretzl** [comment]
Great ;-)

**Pull request merged**
